package com.xtel.cms.ccsp.db.orm;

import java.io.Serializable;
import com.ligerdev.appbase.utils.db.AntTable;
import com.ligerdev.appbase.utils.db.AntColumn;
import java.util.Date;


/*
	- 09/10/2018 11:25:50: Generated by sql
	SELECT * FROM topup_result LIMIT 1
*/
@AntTable(catalog="kns", name="topup_result", label="topup_result", key="")
public class CCSPTopupResult implements Serializable, Cloneable {

	private int id;
	private String msisdn;
	private int fee;
	private int xdate;
	private String note;
	private Date createdTime;
	private String pkgcode;
	private String result;

	public CCSPTopupResult(){
	}
	
	public CCSPTopupResult(int id, String msisdn, int fee, int xdate, String note, Date createdTime, String pkgcode, String result){
		this();
		this.id = id;
		this.msisdn = msisdn;
		this.fee = fee;
		this.xdate = xdate;
		this.note = note;
		this.createdTime = createdTime;
		this.pkgcode = pkgcode;
		this.result = result;
	}
	
	@AntColumn(name="id", auto_increment=true, size=11, label="id")
	public void setId(int id){
		this.id = id;
	}
	
	@AntColumn(name="id", auto_increment=true, size=11, label="id")
	public int getId(){
		return this.id;
	}
	
	@AntColumn(name="msisdn", size=13, label="msisdn")
	public void setMsisdn(String msisdn){
		this.msisdn = msisdn;
	}
	
	@AntColumn(name="msisdn", size=13, label="msisdn")
	public String getMsisdn(){
		return this.msisdn;
	}
	
	@AntColumn(name="fee", size=8, label="fee")
	public void setFee(int fee){
		this.fee = fee;
	}
	
	@AntColumn(name="fee", size=8, label="fee")
	public int getFee(){
		return this.fee;
	}
	
	@AntColumn(name="xdate", size=10, label="xdate")
	public void setXdate(int xdate){
		this.xdate = xdate;
	}
	
	@AntColumn(name="xdate", size=10, label="xdate")
	public int getXdate(){
		return this.xdate;
	}
	
	@AntColumn(name="note", size=45, label="note")
	public void setNote(String note){
		this.note = note;
	}
	
	@AntColumn(name="note", size=45, label="note")
	public String getNote(){
		return this.note;
	}
	
	@AntColumn(name="created_time", size=19, label="created_time")
	public void setCreatedTime(Date createdTime){
		this.createdTime = createdTime;
	}
	
	@AntColumn(name="created_time", size=19, label="created_time")
	public Date getCreatedTime(){
		return this.createdTime;
	}
	
	@AntColumn(name="pkgcode", size=15, label="pkgcode")
	public void setPkgcode(String pkgcode){
		this.pkgcode = pkgcode;
	}
	
	@AntColumn(name="pkgcode", size=15, label="pkgcode")
	public String getPkgcode(){
		return this.pkgcode;
	}
	
	@AntColumn(name="result", size=15, label="result")
	public void setResult(String result){
		this.result = result;
	}
	
	@AntColumn(name="result", size=15, label="result")
	public String getResult(){
		return this.result;
	}
	
	@Override
	public String toString() {
		return "["
			+ "id=" + id
			+ ", msisdn=" + msisdn
			+ ", fee=" + fee
			+ ", xdate=" + xdate
			+ ", note=" + note
			+ ", createdTime=" + createdTime
			+ ", pkgcode=" + pkgcode
			+ ", result=" + result
			+ "]";
	}
	
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}