package com.xxx.hula.logic.db.orm;

import java.io.Serializable;
import com.ligerdev.appbase.utils.db.AntTable;
import com.ligerdev.appbase.utils.db.AntColumn;
import java.util.Date;


/*
	- 13/11/2018 15:38:36: Generated by sql
	SELECT * FROM ctkm1_score LIMIT 1
*/
@AntTable(catalog="kns", name="ctkm1_score", label="ctkm1_score", key="id")
public class Ctkm1Score implements Serializable, Cloneable {

	private int id;
	private String msisdn;
	private String type;
	private String note1;
	private int score;
	private String transid;
	private int xtime;
	private Date createdTime;
	private Date regdate;
	private Date lastupdate;

	public Ctkm1Score(){
	}
	
	public Ctkm1Score(int id, String msisdn, String type, String note1, int score, 
			String transid, int xtime, Date createdTime, Date regdate, Date lastupdate){
		this();
		this.id = id;
		this.msisdn = msisdn;
		this.type = type;
		this.note1 = note1;
		this.score = score;
		this.transid = transid;
		this.xtime = xtime;
		this.createdTime = createdTime;
		this.regdate = regdate;
		this.lastupdate = lastupdate;
	}
	
	@AntColumn(name="id", size=11, label="id")
	public void setId(int id){
		this.id = id;
	}
	
	@AntColumn(name="id", size=11, label="id")
	public int getId(){
		return this.id;
	}
	
	@AntColumn(name="msisdn", size=25, label="msisdn")
	public void setMsisdn(String msisdn){
		this.msisdn = msisdn;
	}
	
	@AntColumn(name="msisdn", size=25, label="msisdn")
	public String getMsisdn(){
		return this.msisdn;
	}
	
	@AntColumn(name="type", size=2, label="type")
	public void setType(String type){
		this.type = type;
	}
	
	@AntColumn(name="type", size=2, label="type")
	public String getType(){
		return this.type;
	}
	
	@AntColumn(name="note1", size=45, label="note1")
	public void setNote1(String note1){
		this.note1 = note1;
	}
	
	@AntColumn(name="note1", size=45, label="note1")
	public String getNote1(){
		return this.note1;
	}
	
	@AntColumn(name="score", size=8, label="score")
	public void setScore(int score){
		this.score = score;
	}
	
	@AntColumn(name="score", size=8, label="score")
	public int getScore(){
		return this.score;
	}
	
	@AntColumn(name="transid", size=45, label="transid")
	public void setTransid(String transid){
		this.transid = transid;
	}
	
	@AntColumn(name="transid", size=45, label="transid")
	public String getTransid(){
		return this.transid;
	}
	
	@AntColumn(name="xtime", size=11, label="xtime")
	public void setXtime(int xtime){
		this.xtime = xtime;
	}
	
	@AntColumn(name="xtime", size=11, label="xtime")
	public int getXtime(){
		return this.xtime;
	}
	
	@AntColumn(name="created_time", size=19, label="created_time")
	public void setCreatedTime(Date createdTime){
		this.createdTime = createdTime;
	}
	
	@AntColumn(name="created_time", size=19, label="created_time")
	public Date getCreatedTime(){
		return this.createdTime;
	}
	
	@AntColumn(name="regdate", size=19, label="regdate")
	public void setRegdate(Date regdate){
		this.regdate = regdate;
	}
	
	@AntColumn(name="regdate", size=19, label="regdate")
	public Date getRegdate(){
		return this.regdate;
	}
	
	@AntColumn(name="lastupdate", size=19, label="lastupdate")
	public Date getLastupdate() {
		return lastupdate;
	}

	@AntColumn(name="lastupdate", size=19, label="lastupdate")
	public void setLastupdate(Date lastupdate) {
		this.lastupdate = lastupdate;
	}
	
	@Override
	public String toString() {
		return "["
			+ "id=" + id
			+ ", msisdn=" + msisdn
			+ ", type=" + type
			+ ", note1=" + note1
			+ ", score=" + score
			+ ", transid=" + transid
			+ ", xtime=" + xtime
			+ ", createdTime=" + createdTime
			+ ", regdate=" + regdate
			+ ", lastupdate=" + lastupdate
			+ "]";
	}
	
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

	
}