package com.xxx.hula.logic.db.orm;

import java.io.Serializable;
import com.ligerdev.appbase.utils.db.AntTable;
import com.ligerdev.appbase.utils.db.AntColumn;
import java.util.Date;


/*
	- 13/11/2018 14:33:25: Generated by sql
	SELECT * FROM ctkm1_his LIMIT 1
*/
@AntTable(catalog="kns", name="ctkm1_his", label="ctkm1_his", key="id")
public class Ctkm1His implements Serializable, Cloneable {

	private int id;
	private String msisdn;
	private String action;
	private int score;
	private String transid;
	private int xdate;
	private int xweek;
	private int xmonth;
	private String pkgcode;
	private Date createdTime;
	private String note1;
	private String note2;
	

	public Ctkm1His(){
		// Ctkm1His score = new Ctkm1His(id, msisdn, action, score, transid, xdate, xweek, xmonth, pkgcode, createdTime, note1, note2);
	}
	
	public Ctkm1His(int id, String msisdn, String action, int score, String transid, int xdate, int xweek, 
			int xmonth, String pkgcode, Date createdTime, String note1, String note2){
		this();
		this.id = id;
		this.msisdn = msisdn;
		this.action = action;
		this.score = score;
		this.transid = transid;
		this.xdate = xdate;
		this.xweek = xweek;
		this.xmonth = xmonth;
		this.pkgcode = pkgcode;
		this.createdTime = createdTime;
		this.note1 = note1;
		this.note2 = note2;
	}
	
	@AntColumn(name="id", auto_increment=true, size=11, label="id")
	public void setId(int id){
		this.id = id;
	}
	
	@AntColumn(name="id", auto_increment=true, size=11, label="id")
	public int getId(){
		return this.id;
	}
	
	@AntColumn(name="msisdn", size=15, label="msisdn")
	public void setMsisdn(String msisdn){
		this.msisdn = msisdn;
	}
	
	@AntColumn(name="msisdn", size=15, label="msisdn")
	public String getMsisdn(){
		return this.msisdn;
	}
	
	@AntColumn(name="action", size=15, label="action")
	public void setAction(String action){
		this.action = action;
	}
	
	@AntColumn(name="action", size=15, label="action")
	public String getAction(){
		return this.action;
	}
	
	@AntColumn(name="score", size=8, label="score")
	public void setScore(int score){
		this.score = score;
	}
	
	@AntColumn(name="score", size=8, label="score")
	public int getScore(){
		return this.score;
	}
	
	@AntColumn(name="transid", size=45, label="transid")
	public void setTransid(String transid){
		this.transid = transid;
	}
	
	@AntColumn(name="transid", size=45, label="transid")
	public String getTransid(){
		return this.transid;
	}
	
	@AntColumn(name="xdate", size=8, label="xdate")
	public void setXdate(int xdate){
		this.xdate = xdate;
	}
	
	@AntColumn(name="xdate", size=8, label="xdate")
	public int getXdate(){
		return this.xdate;
	}
	
	@AntColumn(name="xweek", size=8, label="xweek")
	public void setXweek(int xweek){
		this.xweek = xweek;
	}
	
	@AntColumn(name="xweek", size=8, label="xweek")
	public int getXweek(){
		return this.xweek;
	}
	
	@AntColumn(name="xmonth", size=8, label="xmonth")
	public void setXmonth(int xmonth){
		this.xmonth = xmonth;
	}
	
	@AntColumn(name="xmonth", size=8, label="xmonth")
	public int getXmonth(){
		return this.xmonth;
	}
	
	@AntColumn(name="pkgcode", size=15, label="pkgcode")
	public void setPkgcode(String pkgcode){
		this.pkgcode = pkgcode;
	}
	
	@AntColumn(name="pkgcode", size=15, label="pkgcode")
	public String getPkgcode(){
		return this.pkgcode;
	}
	
	@AntColumn(name="created_time", size=19, label="created_time")
	public void setCreatedTime(Date createdTime){
		this.createdTime = createdTime;
	}
	
	@AntColumn(name="created_time", size=19, label="created_time")
	public Date getCreatedTime(){
		return this.createdTime;
	}
	
	@AntColumn(name="note1", size=45, label="note1")
	public void setNote1(String note1){
		this.note1 = note1;
	}
	
	@AntColumn(name="note1", size=45, label="note1")
	public String getNote1(){
		return this.note1;
	}
	
	@AntColumn(name="note2", size=45, label="note2")
	public void setNote2(String note2){
		this.note2 = note2;
	}
	
	@AntColumn(name="note2", size=45, label="note2")
	public String getNote2(){
		return this.note2;
	}
	
	@Override
	public String toString() {
		return "["
			+ "id=" + id
			+ ", msisdn=" + msisdn
			+ ", action=" + action
			+ ", score=" + score
			+ ", transid=" + transid
			+ ", xdate=" + xdate
			+ ", xweek=" + xweek
			+ ", xmonth=" + xmonth
			+ ", pkgcode=" + pkgcode
			+ ", createdTime=" + createdTime
			+ ", note1=" + note1
			+ ", note2=" + note2
			+ "]";
	}
	
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	} 
}