package com.xtel.cms.base.db.orm;

import java.io.Serializable;
import java.util.Date;

import com.ligerdev.appbase.utils.db.AntColumn;
import com.ligerdev.appbase.utils.db.AntTable;


/*
	- 06/05/2017 20:55:40: Generated by sql
	SELECT * FROM user_cms LIMIT 1
*/
@AntTable(catalog="mobileads", name="user_cms", label="user_cms", key="id")
public class UserCms implements Serializable, Cloneable {

	private int id;
	private String username;
	private String password;
	private String fullname;
	private int usertype;  
	private String phone;
	private int status;
	private Date lastlogin;
	private String address; 
	private String email;
	private String rolename; 	// dữ liệu fix nhóm, để được vào các task nào
	
	private String note1;
	private String note2;
	private String note3;
	private String note4;
	private String note5;
	private String note6;
	private String note7;
	private String note8;
	private String note9;
	
	private int xint1;
	private int xint2;
	private int xint3;
	private int xint4;
	private int xint5;
	private int xint6;
	private int xint7;
	private int xint8;
	private int xint9;
	
	public static int CCSP_USERTYPE_ROOT = 0; // cho full quyền
	public static int CCSP_USERTYPE_ADMIN = 1;		  // xem báo cáo, tác động sub
	public static int CCSP_USERTYPE_NORMAL = 2;		  // tra cứu sub, hủy
	public static int CCSP_USERTYPE_VIEWER = 3;		  // tra cứu sub, chỉ cho xem k cho hủy (loại này có thể chua làm)

	// ext
	private String userTypeStr; // map từ usertype sang
	private Integer maxUnreg = null;
	private long createdTime = System.currentTimeMillis();
	
	public UserCms(){
	}
	
	public UserCms(int id, String username, String password, String fullname, 
			int usertype, String phone, int status, Date lastlogin,
			String address, String email, String rolename){
		this.id = id;
		this.username = username;
		this.password = password;
		this.fullname = fullname;
		this.usertype = usertype;
		this.phone = phone;
		this.status = status;
		this.lastlogin = lastlogin;
		this.address = address;
		this.email = email;
		this.rolename = rolename;
	}
	
	@AntColumn(name="id", auto_increment=true, size=11, label="id")
	public void setId(int id){
		this.id = id;
	}
	
	@AntColumn(name="id", auto_increment=true, size=11, label="id")
	public int getId(){
		return this.id;
	}
	
	@AntColumn(name="username", size=45, label="username")
	public void setUsername(String username){
		this.username = username;
	}
	
	@AntColumn(name="username", size=45, label="username")
	public String getUsername(){
		return this.username;
	}
	
	@AntColumn(name="password", size=100, label="password")
	public void setPassword(String password){
		this.password = password;
	}
	
	@AntColumn(name="password", size=100, label="password")
	public String getPassword(){
		return this.password;
	}
	
	@AntColumn(name="fullname", size=100, label="fullname")
	public void setFullname(String fullname){
		this.fullname = fullname;
	}
	
	@AntColumn(name="fullname", size=100, label="fullname")
	public String getFullname(){
		return this.fullname;
	}
	
	@AntColumn(name="usertype", size=11, label="usertype")
	public void setUsertype(int usertype){
		this.usertype = usertype;
	}
	
	@AntColumn(name="usertype", size=11, label="usertype")
	public int getUsertype(){
		return this.usertype;
	}
	
	@AntColumn(name="phone", size=20, label="phone")
	public void setPhone(String phone){
		this.phone = phone;
	}
	
	@AntColumn(name="phone", size=20, label="phone")
	public String getPhone(){
		return this.phone;
	}
	
	@AntColumn(name="status", size=11, label="status")
	public void setStatus(int status){
		this.status = status;
	}
	
	@AntColumn(name="status", size=11, label="status")
	public int getStatus(){
		return this.status;
	}
	
	@AntColumn(name="lastlogin", size=19, label="lastlogin")
	public void setLastlogin(Date lastlogin){
		this.lastlogin = lastlogin;
	}
	
	@AntColumn(name="lastlogin", size=19, label="lastlogin")
	public Date getLastlogin(){
		return this.lastlogin;
	}
	
	@AntColumn(name="address", size=200, label="address")
	public void setAddress(String address){
		this.address = address;
	}
	
	@AntColumn(name="address", size=200, label="address")
	public String getAddress(){
		return this.address;
	}
	
	@AntColumn(name="email", size=200, label="email")
	public void setEmail(String email){
		this.email = email;
	}
	
	@AntColumn(name="email", size=200, label="email")
	public String getEmail(){
		return this.email;
	}
	
	@AntColumn(name="rolename", size=245, label="rolename")
	public void setRolename(String rolename){
		this.rolename = rolename;
	}
	
	@AntColumn(name="rolename", size=245, label="rolename")
	public String getRolename(){
		return this.rolename;
	}
	

	@AntColumn(name="note1", size=45, label="note1")
	public void setNote1(String note1){
		this.note1 = note1;
	}
	
	@AntColumn(name="note1", size=45, label="note1")
	public String getNote1(){
		return this.note1;
	}
	
	@AntColumn(name="note2", size=45, label="note2")
	public void setNote2(String note2){
		this.note2 = note2;
	}
	
	@AntColumn(name="note2", size=45, label="note2")
	public String getNote2(){
		return this.note2;
	}
	
	@AntColumn(name="note3", size=45, label="note3")
	public void setNote3(String note3){
		this.note3 = note3;
	}
	
	@AntColumn(name="note3", size=45, label="note3")
	public String getNote3(){
		return this.note3;
	}
	
	@AntColumn(name="note4", size=45, label="note4")
	public void setNote4(String note4){
		this.note4 = note4;
	}
	
	@AntColumn(name="note4", size=45, label="note4")
	public String getNote4(){
		return this.note4;
	}
	
	@AntColumn(name="note5", size=45, label="note5")
	public void setNote5(String note5){
		this.note5 = note5;
	}
	
	@AntColumn(name="note5", size=45, label="note5")
	public String getNote5(){
		return this.note5;
	}
	
	@AntColumn(name="note6", size=45, label="note6")
	public void setNote6(String note6){
		this.note6 = note6;
	}
	
	@AntColumn(name="note6", size=45, label="note6")
	public String getNote6(){
		return this.note6;
	}
	
	@AntColumn(name="note7", size=45, label="note7")
	public void setNote7(String note7){
		this.note7 = note7;
	}
	
	@AntColumn(name="note7", size=45, label="note7")
	public String getNote7(){
		return this.note7;
	}
	
	@AntColumn(name="note8", size=45, label="note8")
	public void setNote8(String note8){
		this.note8 = note8;
	}
	
	@AntColumn(name="note8", size=45, label="note8")
	public String getNote8(){
		return this.note8;
	}
	
	@AntColumn(name="note9", size=45, label="note9")
	public void setNote9(String note9){
		this.note9 = note9;
	}
	
	@AntColumn(name="note9", size=45, label="note9")
	public String getNote9(){
		return this.note9;
	}
	
	@AntColumn(name="xint1", size=11, label="xint1")
	public void setXint1(int xint1){
		this.xint1 = xint1;
	}
	
	@AntColumn(name="xint1", size=11, label="xint1")
	public int getXint1(){
		return this.xint1;
	}
	
	@AntColumn(name="xint2", size=11, label="xint2")
	public void setXint2(int xint2){
		this.xint2 = xint2;
	}
	
	@AntColumn(name="xint2", size=11, label="xint2")
	public int getXint2(){
		return this.xint2;
	}
	
	@AntColumn(name="xint3", size=11, label="xint3")
	public void setXint3(int xint3){
		this.xint3 = xint3;
	}
	
	@AntColumn(name="xint3", size=11, label="xint3")
	public int getXint3(){
		return this.xint3;
	}
	
	@AntColumn(name="xint4", size=11, label="xint4")
	public void setXint4(int xint4){
		this.xint4 = xint4;
	}
	
	@AntColumn(name="xint4", size=11, label="xint4")
	public int getXint4(){
		return this.xint4;
	}
	
	@AntColumn(name="xint5", size=11, label="xint5")
	public void setXint5(int xint5){
		this.xint5 = xint5;
	}
	
	@AntColumn(name="xint5", size=11, label="xint5")
	public int getXint5(){
		return this.xint5;
	}
	
	@AntColumn(name="xint6", size=11, label="xint6")
	public void setXint6(int xint6){
		this.xint6 = xint6;
	}
	
	@AntColumn(name="xint6", size=11, label="xint6")
	public int getXint6(){
		return this.xint6;
	}
	
	@AntColumn(name="xint7", size=11, label="xint7")
	public void setXint7(int xint7){
		this.xint7 = xint7;
	}
	
	@AntColumn(name="xint7", size=11, label="xint7")
	public int getXint7(){
		return this.xint7;
	}
	
	@AntColumn(name="xint8", size=11, label="xint8")
	public void setXint8(int xint8){
		this.xint8 = xint8;
	}
	
	@AntColumn(name="xint8", size=11, label="xint8")
	public int getXint8(){
		return this.xint8;
	}
	
	@AntColumn(name="xint9", size=11, label="xint9")
	public void setXint9(int xint9){
		this.xint9 = xint9;
	}
	
	@AntColumn(name="xint9", size=11, label="xint9")
	public int getXint9(){
		return this.xint9;
	}
	
	@Override
	public String toString() {
		return "["
			+ "id=" + id
			+ ", username=" + username
			+ ", password=" + password
			+ ", fullname=" + fullname
			+ ", usertype=" + usertype
			+ ", phone=" + phone
			+ ", status=" + status
			+ ", lastlogin=" + lastlogin
			+ ", address=" + address
			+ ", email=" + email
			+ ", rolename=" + rolename
			
			+ "]";
	}
	
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

	public String getUserTypeStr() {
		return userTypeStr;
	}

	public void setUserTypeStr(String userTypeStr) {
		this.userTypeStr = userTypeStr;
	}

	public Integer getMaxUnreg() {
		return maxUnreg;
	}

	public void setMaxUnreg(Integer maxUnreg) {
		this.maxUnreg = maxUnreg;
	}

	public long getCreatedTime() {
		return createdTime;
	}

	public void setCreatedTime(long createdTime) {
		this.createdTime = createdTime;
	}
}
