package com.xtel.cms.ccsp.db.orm.others;

import java.io.Serializable;

import com.ligerdev.appbase.utils.db.AntColumn;
import com.ligerdev.appbase.utils.db.AntTable;


/*
	- 14/09/2018 05:17:15: Generated by sql
	
select DATE_FORMAT(STR_TO_DATE(hisnote1, '%Y%m%d'), '%Y-%m-%d') date_report, 
COALESCE(sum(case when channel in ("WEB", "WAP") and result = 0 then fee else 0 end), 0) fee_wap,
COALESCE(sum(case when channel in ("SMS") and result = 0 then fee else 0 end), 0) fee_sms,
COALESCE(sum(case when channel in ("IVR") and result = 0 then fee else 0 end), 0) fee_ivr,
COALESCE(sum(case when channel in ("CTKM") and result = 0 then fee else 0 end), 0) fee_ctkm,
COALESCE(sum(case when channel in ("AVB") and result = 0 then fee else 0 end), 0) fee_avb,
COALESCE(sum(case when result = 0 and fee > 0 then fee else 0 end), 0) fee_total  
from his_201809 where result = 0 group by hisnote1  order by hisnote1
*/
@AntTable(catalog="", name="CCSPReportChannel", label="CCSPReportChannel", key="")
public class CCSPReportChannel implements Serializable, Cloneable {

	private String dateReport;
	private String feeWap;
	private String feeSms;
	private String feeOther; 
	// private String feeIvr;
	// private String feeCtkm;
	private String feeAvb;
	private String feeTotal;

	public CCSPReportChannel(){
	}
	
	public CCSPReportChannel(String dateReport, String feeWap, String feeSms, String feeOther, 
			/*String feeIvr, String feeCtkm,*/ String feeAvb, String feeTotal){  
		this();
		this.dateReport = dateReport;
		this.feeWap = feeWap;
		this.feeSms = feeSms;
		// this.feeIvr = feeIvr;
		// this.feeCtkm = feeCtkm;
		this.feeOther = feeOther;
		this.feeAvb = feeAvb;
		this.feeTotal = feeTotal;
	}
	
	@AntColumn(name="date_report", size=10, label="date_report")
	public void setDateReport(String dateReport){
		this.dateReport = dateReport;
	}
	
	@AntColumn(name="date_report", size=10, label="date_report")
	public String getDateReport(){
		return this.dateReport;
	}
	
	@AntColumn(name="fee_wap", size=33, label="fee_wap")
	public void setFeeWap(String feeWap){
		this.feeWap = feeWap;
	}
	
	@AntColumn(name="fee_wap", size=33, label="fee_wap")
	public String getFeeWap(){
		return this.feeWap;
	}
	
	@AntColumn(name="fee_sms", size=33, label="fee_sms")
	public void setFeeSms(String feeSms){
		this.feeSms = feeSms;
	}
	
	@AntColumn(name="fee_sms", size=33, label="fee_sms")
	public String getFeeSms(){
		return this.feeSms;
	}
	
	/*@AntColumn(name="fee_ivr", size=33, label="fee_ivr")
	public void setFeeIvr(String feeIvr){
		this.feeIvr = feeIvr;
	}
	
	@AntColumn(name="fee_ivr", size=33, label="fee_ivr")
	public String getFeeIvr(){
		return this.feeIvr;
	}*/
	
	/*@AntColumn(name="fee_ctkm", size=33, label="fee_ctkm")
	public void setFeeCtkm(String feeCtkm){
		this.feeCtkm = feeCtkm;
	}
	
	@AntColumn(name="fee_ctkm", size=33, label="fee_ctkm")
	public String getFeeCtkm(){
		return this.feeCtkm;
	}*/
	
	@AntColumn(name="fee_avb", size=33, label="fee_avb")
	public void setFeeAvb(String feeAvb){
		this.feeAvb = feeAvb;
	}
	
	@AntColumn(name="fee_avb", size=33, label="fee_avb")
	public String getFeeAvb(){
		return this.feeAvb;
	}
	
	@AntColumn(name="fee_total", size=33, label="fee_total")
	public void setFeeTotal(String feeTotal){
		this.feeTotal = feeTotal;
	}
	
	@AntColumn(name="fee_total", size=33, label="fee_total")
	public String getFeeTotal(){
		return this.feeTotal;
	}
	
	@AntColumn(name="fee_other", size=33, label="fee_other")
	public String getFeeOther() {
		return feeOther;
	}

	@AntColumn(name="fee_other", size=33, label="fee_other")
	public void setFeeOther(String feeOther) {
		this.feeOther = feeOther;
	}
	
	@Override
	public String toString() {
		return "["
			+ "dateReport=" + dateReport
			+ ", feeWap=" + feeWap
			+ ", feeSms=" + feeSms
		//	+ ", feeIvr=" + feeIvr
		//	+ ", feeCtkm=" + feeCtkm
			+ ", feeOther=" + feeOther
			+ ", feeAvb=" + feeAvb
			+ ", feeTotal=" + feeTotal
			+ "]";
	}
	
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

	
}