package com.xtel.cms.ccsp.db.orm.others;

import java.io.Serializable;
import com.ligerdev.appbase.utils.db.AntTable;
import com.ligerdev.appbase.utils.db.AntColumn;


/*
	- 28/05/2019 18:28:35: Generated by sql
	select DATE_FORMAT(STR_TO_DATE(hisnote3, '%Y%m%d'), '%Y-%m-%d') date_report, pkg_code, count(fee) count, sum(fee) fee from his_201905 where result = 0 group by date_report, pkg_code order by date_report desc
*/
@AntTable(catalog="", name="CCSPReportPKG", label="CCSPReportPKG", key="")
public class CCSPReportSubService implements Serializable, Cloneable {

	private String dateReport;
	private String subService;
	private String fee;
	
	public CCSPReportSubService(){
	}
	
	public CCSPReportSubService(String dateReport, String subService, String fee){
		this();
		this.dateReport = dateReport;
		this.setSubService(subService);
		this.fee = fee;
	}
	
	@AntColumn(name="date_report", size=10, label="date_report")
	public void setDateReport(String dateReport){
		this.dateReport = dateReport;
	}
	
	@AntColumn(name="date_report", size=10, label="date_report")
	public String getDateReport(){
		return this.dateReport;
	} 
	
	@AntColumn(name="fee", size=33, label="fee")
	public void setFee(String fee){
		this.fee = fee;
	}
	
	@AntColumn(name="fee", size=33, label="fee")
	public String getFee(){
		return this.fee;
	}
	
	@AntColumn(name="sub_service", size=33, label="sub_service")
	public String getSubService() {
		return subService;
	}

	@AntColumn(name="sub_service", size=33, label="sub_service")
	public void setSubService(String subService) {
		this.subService = subService;
	}  
	 
	@Override
	public String toString() {
		return "["
			+ "dateReport=" + dateReport
			+ ", subService=" + subService
			+ ", fee=" + fee
			+ "]";  
	}
	
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	} 
}