package com.xtel.cms.ccsp.db.orm.others;

import java.io.Serializable;
import com.ligerdev.appbase.utils.db.AntTable;
import com.ligerdev.appbase.utils.db.AntColumn;


/*
	- 28/05/2019 18:28:35: Generated by sql
	select DATE_FORMAT(STR_TO_DATE(hisnote3, '%Y%m%d'), '%Y-%m-%d') date_report, pkg_code, count(fee) count, sum(fee) fee from his_201905 where result = 0 group by date_report, pkg_code order by date_report desc
*/
@AntTable(catalog="", name="CCSPReportPKG", label="CCSPReportPKG", key="")
public class CCSPReportPKG implements Serializable, Cloneable {

	private String dateReport;
	private String pkgCode;
	private int count;
	private String fee;
	
	// ext
	private String feeDesc = null;
	private String pkgDesc = null;
	private String note = null;
	
	public CCSPReportPKG(){
	}
	
	public CCSPReportPKG(String dateReport, String pkgCode, int count, String fee){
		this();
		this.dateReport = dateReport;
		this.pkgCode = pkgCode;
		this.count = count;
		this.fee = fee;
	}
	
	@AntColumn(name="date_report", size=10, label="date_report")
	public void setDateReport(String dateReport){
		this.dateReport = dateReport;
	}
	
	@AntColumn(name="date_report", size=10, label="date_report")
	public String getDateReport(){
		return this.dateReport;
	}
	
	@AntColumn(name="pkg_code", size=30, label="pkg_code")
	public void setPkgCode(String pkgCode){
		this.pkgCode = pkgCode;
	}
	
	@AntColumn(name="pkg_code", size=30, label="pkg_code")
	public String getPkgCode(){
		return this.pkgCode;
	}
	
	@AntColumn(name="count", size=21, label="count")
	public void setCount(int count){
		this.count = count;
	}
	
	@AntColumn(name="count", size=21, label="count")
	public int getCount(){
		return this.count;
	}
	
	@AntColumn(name="fee", size=33, label="fee")
	public void setFee(String fee){
		this.fee = fee;
	}
	
	@AntColumn(name="fee", size=33, label="fee")
	public String getFee(){
		return this.fee;
	}
	
	public String getPkgDesc() {
		return pkgDesc;
	}

	public void setPkgDesc(String pkgDesc) { 
		this.pkgDesc = pkgDesc; 
	}

	public String getFeeDesc() { 
		return feeDesc; 
	}

	public void setFeeDesc(String feeDesc) {
		this.feeDesc = feeDesc;
	}
	
	@Override
	public String toString() {
		return "["
			+ "dateReport=" + dateReport
			+ ", pkgCode=" + pkgCode
			+ ", count=" + count
			+ ", fee=" + fee
			+ "]";  
	}
	
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	} 
}