package com.xtel.cms.ccsp.db.orm.others;

import java.io.Serializable;

import com.ligerdev.appbase.utils.db.AntColumn;
import com.ligerdev.appbase.utils.db.AntTable;


/*
	- 14/09/2018 04:45:24: Generated by sql
	select hisnote1 date_report, 
COALESCE(sum(case when action in ("FirstREG", "ReREG") and result = 0 then fee else 0 end), 0) fee_dk,
COALESCE(sum(case when action in ("RENEW") and result = 0 then fee else 0 end), 0) fee_renew,
COALESCE(sum(case when action in ("CONTENT") and result = 0 then fee else 0 end), 0) fee_content, 
COALESCE(sum(case when result = 0 and fee > 0 then fee else 0 end), 0) fee_total  
from his_201809 where result = 0 group by hisnote1  order by hisnote1
*/
@AntTable(catalog="", name="CCSPReportFee", label="CCSPReportFee", key="")
public class CCSPReportFee implements Serializable, Cloneable {

	private String dateReport;
	private String feeDk;
	private String feeRenew;
	private String feeContent;
	private String feeTotal;

	public CCSPReportFee(){
	}
	
	public CCSPReportFee(String dateReport, String feeDk, String feeRenew, String feeContent, String feeTotal){
		this();
		this.dateReport = dateReport;
		this.feeDk = feeDk;
		this.feeRenew = feeRenew;
		this.feeContent = feeContent;
		this.feeTotal = feeTotal;
	}
	
	@AntColumn(name="date_report", size=30, label="date_report")
	public void setDateReport(String dateReport){
		this.dateReport = dateReport;
	}
	
	@AntColumn(name="date_report", size=30, label="date_report")
	public String getDateReport(){
		return this.dateReport;
	}
	
	@AntColumn(name="fee_dk", size=33, label="fee_dk")
	public void setFeeDk(String feeDk){
		this.feeDk = feeDk;
	}
	
	@AntColumn(name="fee_dk", size=33, label="fee_dk")
	public String getFeeDk(){
		return this.feeDk;
	}
	
	@AntColumn(name="fee_renew", size=33, label="fee_renew")
	public void setFeeRenew(String feeRenew){
		this.feeRenew = feeRenew;
	}
	
	@AntColumn(name="fee_renew", size=33, label="fee_renew")
	public String getFeeRenew(){
		return this.feeRenew;
	}
	
	@AntColumn(name="fee_content", size=33, label="fee_content")
	public void setFeeContent(String feeContent){
		this.feeContent = feeContent;
	}
	
	@AntColumn(name="fee_content", size=33, label="fee_content")
	public String getFeeContent(){
		return this.feeContent;
	}
	
	@AntColumn(name="fee_total", size=33, label="fee_total")
	public void setFeeTotal(String feeTotal){
		this.feeTotal = feeTotal;
	}
	
	@AntColumn(name="fee_total", size=33, label="fee_total")
	public String getFeeTotal(){
		return this.feeTotal;
	}
	
	@Override
	public String toString() {
		return "["
			+ "dateReport=" + dateReport
			+ ", feeDk=" + feeDk
			+ ", feeRenew=" + feeRenew
			+ ", feeContent=" + feeContent
			+ ", feeTotal=" + feeTotal
			+ "]";
	}
	
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}