package com.xtel.cms.ccsp.db.orm.others;

import java.io.Serializable;

import com.ligerdev.appbase.utils.db.AntColumn;
import com.ligerdev.appbase.utils.db.AntTable;


/*
	- 14/09/2018 05:26:13: Generated by sql
	select DATE_FORMAT(STR_TO_DATE(hisnote1, '%Y%m%d'), '%Y-%m-%d') date_report, 
COALESCE(sum(case when action in ("FirstREG", "ReREG") and result = 0  and channel = "SMS" then 1 else 0 end), 0) dk_sms,
COALESCE(sum(case when action in ("FirstREG", "ReREG") and result = 0  and channel = "WAP" then 1 else 0 end), 0) dk_wap,
COALESCE(sum(case when action in ("FirstREG", "ReREG") and result = 0  and channel = "CTKM" then 1 else 0 end), 0) dk_ctkm,
COALESCE(sum(case when action in ("FirstREG", "ReREG") and result = 0  and channel = "IVR" then 1 else 0 end), 0) dk_ivr,
COALESCE(sum(case when action in ("FirstREG", "ReREG") and result = 0  and channel = "VBC" then 1 else 0 end), 0) dk_vbc,
COALESCE(sum(case when action in ("FirstREG", "ReREG") and result = 0 then 1 else 0 end), 0) dk_total,

COALESCE(sum(case when action in ("UNREG") and result = 0 and channel = "SMS" then 1 else 0 end), 0) huy_sms,
COALESCE(sum(case when action in ("UNREG") and result = 0 and channel = "CP" then 1 else 0 end), 0) huy_cskh,
COALESCE(sum(case when action in ("UNREG") and result = 0 then 1 else 0 end), 0) huy_total 
from his_201809 where result = 0 group by hisnote1  order by hisnote1
*/
@AntTable(catalog="", name="CCSPReportREG", label="CCSPReportREG", key="")
public class CCSPReportREG implements Serializable, Cloneable {

	private String dateReport;
	private String dkSms;
	private String dkWap;
	// private String dkCtkm;
	// private String dkIvr; 
	private String dkVbc;
	private String dkTotal;
	private String huySms;
	private String huyCskh;
	private String huyHt;
	private String huyToday;
	private String huyTotal;

	// ext
	private String changeSubs;
	private String huyOther;
	
	public CCSPReportREG(){
	}
	
	public CCSPReportREG(String dateReport, String dkSms, String dkWap, /*String dkCtkm, String dkIvr, */String dkVbc, 
			String dkTotal, String huySms, String huyCskh, String huyHt, String huyToday, String huyTotal){
		this();
		this.dateReport = dateReport;
		this.dkSms = dkSms;
		this.dkWap = dkWap;
		// this.dkCtkm = dkCtkm;
		// this.dkIvr = dkIvr;
		this.dkVbc = dkVbc;
		this.dkTotal = dkTotal;
		this.huySms = huySms;
		this.huyCskh = huyCskh;
		this.huyTotal = huyTotal;
		this.huyHt = huyHt;
		this.huyToday = huyToday;
	}
	
	@AntColumn(name="date_report", size=10, label="date_report")
	public void setDateReport(String dateReport){
		this.dateReport = dateReport;
	}
	
	@AntColumn(name="date_report", size=10, label="date_report")
	public String getDateReport(){
		return this.dateReport;
	}
	
	@AntColumn(name="dk_sms", size=24, label="dk_sms")
	public void setDkSms(String dkSms){
		this.dkSms = dkSms;
	}
	
	@AntColumn(name="dk_sms", size=24, label="dk_sms")
	public String getDkSms(){
		return this.dkSms;
	}
	
	@AntColumn(name="dk_wap", size=24, label="dk_wap")
	public void setDkWap(String dkWap){
		this.dkWap = dkWap;
	}
	
	@AntColumn(name="dk_wap", size=24, label="dk_wap")
	public String getDkWap(){
		return this.dkWap;
	}
	
	/*@AntColumn(name="dk_ctkm", size=24, label="dk_ctkm")
	public void setDkCtkm(String dkCtkm){
		this.dkCtkm = dkCtkm;
	}
	
	@AntColumn(name="dk_ctkm", size=24, label="dk_ctkm")
	public String getDkCtkm(){
		return this.dkCtkm;
	}*/
	
	/*@AntColumn(name="dk_ivr", size=24, label="dk_ivr")
	public void setDkIvr(String dkIvr){
		this.dkIvr = dkIvr;
	}
	
	@AntColumn(name="dk_ivr", size=24, label="dk_ivr")
	public String getDkIvr(){
		return this.dkIvr;
	}*/
	
	@AntColumn(name="dk_vbc", size=24, label="dk_vbc")
	public void setDkVbc(String dkVbc){
		this.dkVbc = dkVbc;
	}
	
	@AntColumn(name="dk_vbc", size=24, label="dk_vbc")
	public String getDkVbc(){
		return this.dkVbc;
	}
	
	@AntColumn(name="dk_total", size=24, label="dk_total")
	public void setDkTotal(String dkTotal){
		this.dkTotal = dkTotal;
	}
	
	@AntColumn(name="dk_total", size=24, label="dk_total")
	public String getDkTotal(){
		return this.dkTotal;
	}
	
	@AntColumn(name="huy_sms", size=24, label="huy_sms")
	public void setHuySms(String huySms){
		this.huySms = huySms;
	}
	
	@AntColumn(name="huy_sms", size=24, label="huy_sms")
	public String getHuySms(){
		return this.huySms;
	}
	
	@AntColumn(name="huy_cskh", size=24, label="huy_cskh")
	public void setHuyCskh(String huyCskh){
		this.huyCskh = huyCskh;
	}
	
	@AntColumn(name="huy_cskh", size=24, label="huy_cskh")
	public String getHuyCskh(){
		return this.huyCskh;
	}
	
	@AntColumn(name="huy_total", size=24, label="huy_total")
	public void setHuyTotal(String huyTotal){
		this.huyTotal = huyTotal;
	}
	
	@AntColumn(name="huy_total", size=24, label="huy_total")
	public String getHuyTotal(){
		return this.huyTotal;
	}
	
	@AntColumn(name="huy_ht", size=24, label="huy_ht")
	public String getHuyHt() {
		return huyHt;
	}

	@AntColumn(name="huy_ht", size=24, label="huy_ht")
	public void setHuyHt(String huyHt) {
		this.huyHt = huyHt;
	}
	
	@AntColumn(name="huy_today", size=24, label="huy_today")
	public String getHuyToday() {
		return huyToday;
	}

	@AntColumn(name="huy_today", size=24, label="huy_today")
	public void setHuyToday(String huyToday) {
		this.huyToday = huyToday;
	}
	
	@Override
	public String toString() {
		return "["
			+ "dateReport=" + dateReport
			+ ", dkSms=" + dkSms
			+ ", dkWap=" + dkWap
		//	+ ", dkCtkm=" + dkCtkm
		//	+ ", dkIvr=" + dkIvr
			+ ", dkVbc=" + dkVbc
			+ ", dkTotal=" + dkTotal
			+ ", huySms=" + huySms
			+ ", huyCskh=" + huyCskh
			+ ", huyHt=" + huyHt
			+ ", huyToday=" + huyToday
			+ ", huyTotal=" + huyTotal
			+ "]";
	}
	
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

	public String getChangeSubs() {
		return changeSubs;
	}

	public void setChangeSubs(String changeSubs) {
		this.changeSubs = changeSubs;
	}

	public String getHuyOther() {
		return huyOther;
	}

	public void setHuyOther(String huyOther) {
		this.huyOther = huyOther;
	}

	
}