package com.xtel.cms.ccsp.db.orm.others;

import java.io.Serializable;

import com.ligerdev.appbase.utils.db.AntTable;
import com.ligerdev.appbase.utils.db.AntColumn;

import java.util.Date;


/*
    - 09/05/2019 11:31:44: Generated by sql
	select
x.id,x.name,x.begin_time,x.end_time,x.noidung,'' time_ctkm,
x.count_dk,
x.count_huy,
x.count_active,
x.sum_topupfee,
y.count_psc,
z.sum_fee_kybaocao,
z.sum_fee_luyke
from
(select 
a.id,
sum(1) count_dk,
sum(case when b.deactive24h_time is not null and 1=1 then 1 else 0 end) count_huy,
sum(case when b.deactive24h_time is null and 1=1 then 1 else 0 end) count_active,
sum(case when (b.deactive24h_time is null or b.deactive24h_time<b.created_time+interval 1 day) and (b.renew24h_time is not null) and b.kmtq_id is not null and c.status=2 then c.topup_fee else 0 end) sum_topupfee,
a.name,a.begin_time,a.end_time,a.noidung 
from dm_ctkm a join stats_kmtq b 
on a.category=b.category
left join kmtq c 
on b.created_time=c.created_time and b.msisdn=c.msisdn
where a.status=1 group by a.id) x
join
(select c.id,count(c.msisdn) count_psc
from
(select 
distinct a.id,b.msisdn
from dm_ctkm a 
join his_renew_kmtq b
on a.category=b.category
where a.status=1 and 1=1)c
group by c.id) y
on x.id=y.id
join
(select 
a.id,
sum(case when 1=1 and 1=1 then fee else 0 end) sum_fee_kybaocao,
sum(case when 1=1 and 1=1 then fee else 0 end) sum_fee_luyke
from dm_ctkm a 
join his_renew_kmtq b
on a.category=b.category
where a.status=1 and 1=1
group by a.id) z
on y.id=z.id
*/
@AntTable(catalog = "", name = "ThongKeDanhGiaHieuQuaCTKMBean", label = "ThongKeDanhGiaHieuQuaCTKMBean", key = "id")
public class ThongKeDanhGiaHieuQuaCTKMBean implements Serializable, Cloneable {

    private int id;
    private String name;
    private Date beginTime;
    private Date endTime;
    private String noidung;
    private String timeCtkm;
    private String countDk;
    private String countHuy;
    private String countActive;
    private String sumTopupfee;
    private String countPsc;
    private String sumFeeKybaocao;
    private String sumFeeLuyke;
    private int chenhlech;

    public ThongKeDanhGiaHieuQuaCTKMBean() {
    }

    public ThongKeDanhGiaHieuQuaCTKMBean(int id, String name, Date beginTime, Date endTime, String noidung, String timeCtkm, String countDk, String countHuy, String countActive, String sumTopupfee, String countPsc, String sumFeeKybaocao, String sumFeeLuyke, int chenhlech) {
        this.id = id;
        this.name = name;
        this.beginTime = beginTime;
        this.endTime = endTime;
        this.noidung = noidung;
        this.timeCtkm = timeCtkm;
        this.countDk = countDk;
        this.countHuy = countHuy;
        this.countActive = countActive;
        this.sumTopupfee = sumTopupfee;
        this.countPsc = countPsc;
        this.sumFeeKybaocao = sumFeeKybaocao;
        this.sumFeeLuyke = sumFeeLuyke;
        this.chenhlech = chenhlech;
    }

    @AntColumn(name = "id", size = 11, label = "id")
    public void setId(int id) {
        this.id = id;
    }

    @AntColumn(name = "id", size = 11, label = "id")
    public int getId() {
        return this.id;
    }

    @AntColumn(name = "name", size = 100, label = "name")
    public void setName(String name) {
        this.name = name;
    }

    @AntColumn(name = "name", size = 100, label = "name")
    public String getName() {
        return this.name;
    }

    @AntColumn(name = "begin_time", size = 19, label = "begin_time")
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    @AntColumn(name = "begin_time", size = 19, label = "begin_time")
    public Date getBeginTime() {
        return this.beginTime;
    }

    @AntColumn(name = "end_time", size = 19, label = "end_time")
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    @AntColumn(name = "end_time", size = 19, label = "end_time")
    public Date getEndTime() {
        return this.endTime;
    }

    @AntColumn(name = "noidung", size = 100, label = "noidung")
    public void setNoidung(String noidung) {
        this.noidung = noidung;
    }

    @AntColumn(name = "noidung", size = 100, label = "noidung")
    public String getNoidung() {
        return this.noidung;
    }

    @AntColumn(name = "time_ctkm", size = 0, label = "time_ctkm")
    public void setTimeCtkm(String timeCtkm) {
        this.timeCtkm = timeCtkm;
    }

    @AntColumn(name = "time_ctkm", size = 0, label = "time_ctkm")
    public String getTimeCtkm() {
        return this.timeCtkm;
    }

    @AntColumn(name = "count_dk", size = 24, label = "count_dk")
    public void setCountDk(String countDk) {
        this.countDk = countDk;
    }

    @AntColumn(name = "count_dk", size = 24, label = "count_dk")
    public String getCountDk() {
        return this.countDk;
    }

    @AntColumn(name = "count_huy", size = 24, label = "count_huy")
    public void setCountHuy(String countHuy) {
        this.countHuy = countHuy;
    }

    @AntColumn(name = "count_huy", size = 24, label = "count_huy")
    public String getCountHuy() {
        return this.countHuy;
    }

    @AntColumn(name = "count_active", size = 24, label = "count_active")
    public void setCountActive(String countActive) {
        this.countActive = countActive;
    }

    @AntColumn(name = "count_active", size = 24, label = "count_active")
    public String getCountActive() {
        return this.countActive;
    }

    @AntColumn(name = "sum_topupfee", size = 33, label = "sum_topupfee")
    public void setSumTopupfee(String sumTopupfee) {
        this.sumTopupfee = sumTopupfee;
    }

    @AntColumn(name = "sum_topupfee", size = 33, label = "sum_topupfee")
    public String getSumTopupfee() {
        return this.sumTopupfee;
    }

    @AntColumn(name = "count_psc", size = 21, label = "count_psc")
    public void setCountPsc(String countPsc) {
        this.countPsc = countPsc;
    }

    @AntColumn(name = "count_psc", size = 21, label = "count_psc")
    public String getCountPsc() {
        return this.countPsc;
    }

    @AntColumn(name = "sum_fee_kybaocao", size = 33, label = "sum_fee_kybaocao")
    public void setSumFeeKybaocao(String sumFeeKybaocao) {
        this.sumFeeKybaocao = sumFeeKybaocao;
    }

    @AntColumn(name = "sum_fee_kybaocao", size = 33, label = "sum_fee_kybaocao")
    public String getSumFeeKybaocao() {
        return this.sumFeeKybaocao;
    }

    @AntColumn(name = "sum_fee_luyke", size = 33, label = "sum_fee_luyke")
    public void setSumFeeLuyke(String sumFeeLuyke) {
        this.sumFeeLuyke = sumFeeLuyke;
    }

    @AntColumn(name = "sum_fee_luyke", size = 33, label = "sum_fee_luyke")
    public String getSumFeeLuyke() {
        return this.sumFeeLuyke;
    }

    @AntColumn(name = "chenhlech", size = 21, label = "chenhlech")
    public void setChenhlech(int chenhlech) {
        this.chenhlech = chenhlech;
    }

    @AntColumn(name = "chenhlech", size = 21, label = "chenhlech")
    public int getChenhlech() {
        return this.chenhlech;
    }

    @Override
    public String toString() {
        return "["
                + "id=" + id
                + ", name=" + name
                + ", beginTime=" + beginTime
                + ", endTime=" + endTime
                + ", noidung=" + noidung
                + ", timeCtkm=" + timeCtkm
                + ", countDk=" + countDk
                + ", countHuy=" + countHuy
                + ", countActive=" + countActive
                + ", sumTopupfee=" + sumTopupfee
                + ", countPsc=" + countPsc
                + ", sumFeeKybaocao=" + sumFeeKybaocao
                + ", sumFeeLuyke=" + sumFeeLuyke
                + "]";
    }

    @Override
    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }
}