package com.xtel.cms.ccsp.db.orm.others;

import java.io.Serializable;
import com.ligerdev.appbase.utils.db.AntTable;
import com.ligerdev.appbase.utils.db.AntColumn;
import java.util.Date;


/*
	- 09/05/2019 10:55:24: Generated by sql
	select
a.msisdn,
a.created_time,
case when (a.deactive24h_time is null or a.deactive24h_time<a.created_time+interval 1 day) and (a.renew24h_time is not null) then 'x' else '' end dudk,
case when (a.deactive24h_time is null or a.deactive24h_time<a.created_time+interval 1 day) and (a.renew24h_time is null) then 'x' else '' end chuadapung,
case when a.deactive24h_time<a.created_time+interval 1 day then 'x' else '' end huytruoc24h,
b.topup_time,c.topup_fee,
case when b.status=2 then 'x' else '' end resultok,
case when b.status=3 then 'x' else '' end resultnok
from
dm_ctkm c
join stats_kmtq a
on c.category=a.category
left join kmtq b
on a.kmtq_id=b.id

*/
@AntTable(catalog="", name="ThueBaoDangKyCTKMBean", label="ThueBaoDangKyCTKMBean", key="id")
public class ThueBaoDangKyCTKMBean implements Serializable, Cloneable {

	private String msisdn;
	private Date createdTime;
	private String dudk;
	private String chuadapung;
	private String huytruoc24h;
	private Date topupTime;
	private int topupFee;
	private String resultok;
	private String resultnok;

	public ThueBaoDangKyCTKMBean(){
	}

	public ThueBaoDangKyCTKMBean(String msisdn, Date createdTime, String dudk, String chuadapung, String huytruoc24h, Date topupTime, int topupFee, String resultok, String resultnok){
		this();
		this.msisdn = msisdn;
		this.createdTime = createdTime;
		this.dudk = dudk;
		this.chuadapung = chuadapung;
		this.huytruoc24h = huytruoc24h;
		this.topupTime = topupTime;
		this.topupFee = topupFee;
		this.resultok = resultok;
		this.resultnok = resultnok;
	}

	@AntColumn(name="msisdn", size=20, label="msisdn")
	public void setMsisdn(String msisdn){
		this.msisdn = msisdn;
	}

	@AntColumn(name="msisdn", size=20, label="msisdn")
	public String getMsisdn(){
		return this.msisdn;
	}

	@AntColumn(name="created_time", size=19, label="created_time")
	public void setCreatedTime(Date createdTime){
		this.createdTime = createdTime;
	}

	@AntColumn(name="created_time", size=19, label="created_time")
	public Date getCreatedTime(){
		return this.createdTime;
	}

	@AntColumn(name="dudk", size=1, label="dudk")
	public void setDudk(String dudk){
		this.dudk = dudk;
	}

	@AntColumn(name="dudk", size=1, label="dudk")
	public String getDudk(){
		return this.dudk;
	}

	@AntColumn(name="chuadapung", size=1, label="chuadapung")
	public void setChuadapung(String chuadapung){
		this.chuadapung = chuadapung;
	}

	@AntColumn(name="chuadapung", size=1, label="chuadapung")
	public String getChuadapung(){
		return this.chuadapung;
	}

	@AntColumn(name="huytruoc24h", size=1, label="huytruoc24h")
	public void setHuytruoc24h(String huytruoc24h){
		this.huytruoc24h = huytruoc24h;
	}

	@AntColumn(name="huytruoc24h", size=1, label="huytruoc24h")
	public String getHuytruoc24h(){
		return this.huytruoc24h;
	}

	@AntColumn(name="topup_time", size=19, label="topup_time")
	public void setTopupTime(Date topupTime){
		this.topupTime = topupTime;
	}

	@AntColumn(name="topup_time", size=19, label="topup_time")
	public Date getTopupTime(){
		return this.topupTime;
	}

	@AntColumn(name="topup_fee", size=5, label="topup_fee")
	public void setTopupFee(int topupFee){
		this.topupFee = topupFee;
	}

	@AntColumn(name="topup_fee", size=5, label="topup_fee")
	public int getTopupFee(){
		return this.topupFee;
	}

	@AntColumn(name="resultok", size=1, label="resultok")
	public void setResultok(String resultok){
		this.resultok = resultok;
	}

	@AntColumn(name="resultok", size=1, label="resultok")
	public String getResultok(){
		return this.resultok;
	}

	@AntColumn(name="resultnok", size=1, label="resultnok")
	public void setResultnok(String resultnok){
		this.resultnok = resultnok;
	}

	@AntColumn(name="resultnok", size=1, label="resultnok")
	public String getResultnok(){
		return this.resultnok;
	}

	@Override
	public String toString() {
		return "["
				+ "msisdn=" + msisdn
				+ ", createdTime=" + createdTime
				+ ", dudk=" + dudk
				+ ", chuadapung=" + chuadapung
				+ ", huytruoc24h=" + huytruoc24h
				+ ", topupTime=" + topupTime
				+ ", topupFee=" + topupFee
				+ ", resultok=" + resultok
				+ ", resultnok=" + resultnok
				+ "]";
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}