package com.xtel.cms.ccsp.db.orm.others;

import java.io.Serializable;
import com.ligerdev.appbase.utils.db.AntTable;
import com.ligerdev.appbase.utils.db.AntColumn;


/*
	- 19/06/2019 12:41:18: Generated by sql
	select time_report, registered, unregistered, 
(select count(id) from ns_action where star_id=a.top_pl1 and xdate=a.xdate) top_pl1, 
(select count(id) from ns_action where star_id=a.top_pl2 and xdate=a.xdate) top_pl2, 
(select count(id) from ns_action where star_id=a.top_pl3 and xdate=a.xdate) top_pl3, 
(select count(id) from ns_action where star_id=a.top_pl4 and xdate=a.xdate) top_pl4, 
sub_active total_charge_sub, total_fee 
from 
(
   select b.*, DATE_FORMAT(time,'%d/%m/%Y') time_report, 
       (case when pkg_code = 'XEM1' then 'XEM1 (Ng?)' when pkg_code = 'XEM7' then 'XEM7 (Tuần)'  when pkg_code = 'TS' then 'Tranh t? Showbiz (Ng?)' else '' end) lable01, 
        sub_active, registered, reg_sms, reg_ivr, reg_wap, unregistered, total_call, total_call_fee, total_charge_sub, charge_sub_success, ratio, total_sub_fee, total_fee
   from statistic_daily_revenue_details a join ns_topstar_dayli b on b.xdate = DATE_FORMAT(time,'%Y%m%d') 
   where pkg_code = 'TS' and b.xdate >= 20190610 and b.xdate <= 20190620 
        order by xdate desc
) a
*/
@AntTable(catalog="", name="TranhTaiShowbizReportBean", label="TranhTaiShowbizReportBean", key="")
public class TranhTaiShowbizReportBean implements Serializable, Cloneable {

	private String timeReport;
	private int registered;
	private int unregistered;
	private Integer topPl1;
	private Integer topPl2;
	private Integer topPl3;
	private Integer topPl4;
	private int totalChargeSub;
	private int totalFee;

	public TranhTaiShowbizReportBean(){
	}
	
	public TranhTaiShowbizReportBean(String timeReport, int registered, int unregistered, Integer topPl1, Integer topPl2, Integer topPl3
			, Integer topPl4, int totalChargeSub, int totalFee){
		this();
		this.timeReport = timeReport;
		this.registered = registered;
		this.unregistered = unregistered;
		this.topPl1 = topPl1;
		this.topPl2 = topPl2;
		this.topPl3 = topPl3;
		this.topPl4 = topPl4;
		this.totalChargeSub = totalChargeSub;
		this.totalFee = totalFee;
	}
	
	@AntColumn(name="time_report", size=10, label="time_report")
	public void setTimeReport(String timeReport){
		this.timeReport = timeReport;
	}
	
	@AntColumn(name="time_report", size=10, label="time_report")
	public String getTimeReport(){
		return this.timeReport;
	}
	
	@AntColumn(name="registered", size=11, label="registered")
	public void setRegistered(int registered){
		this.registered = registered;
	}
	
	@AntColumn(name="registered", size=11, label="registered")
	public int getRegistered(){
		return this.registered;
	}
	
	@AntColumn(name="unregistered", size=11, label="unregistered")
	public void setUnregistered(int unregistered){
		this.unregistered = unregistered;
	}
	
	@AntColumn(name="unregistered", size=11, label="unregistered")
	public int getUnregistered(){
		return this.unregistered;
	}
	
	@AntColumn(name="top_pl1", size=21, label="top_pl1")
	public void setTopPl1(Integer topPl1){
		this.topPl1 = topPl1;
	}
	
	@AntColumn(name="top_pl1", size=21, label="top_pl1")
	public Integer getTopPl1(){
		return this.topPl1;
	}
	
	@AntColumn(name="top_pl2", size=21, label="top_pl2")
	public void setTopPl2(Integer topPl2){
		this.topPl2 = topPl2;
	}
	
	@AntColumn(name="top_pl2", size=21, label="top_pl2")
	public Integer getTopPl2(){
		return this.topPl2;
	}
	
	@AntColumn(name="top_pl3", size=21, label="top_pl3")
	public void setTopPl3(Integer topPl3){
		this.topPl3 = topPl3;
	}
	
	@AntColumn(name="top_pl3", size=21, label="top_pl3")
	public Integer getTopPl3(){
		return this.topPl3;
	}
	
	@AntColumn(name="top_pl4", size=21, label="top_pl4")
	public void setTopPl4(Integer topPl4){
		this.topPl4 = topPl4;
	}
	
	@AntColumn(name="top_pl4", size=21, label="top_pl4")
	public Integer getTopPl4(){
		return this.topPl4;
	}
	
	@AntColumn(name="total_charge_sub", size=11, label="total_charge_sub")
	public void setTotalChargeSub(int totalChargeSub){
		this.totalChargeSub = totalChargeSub;
	}
	
	@AntColumn(name="total_charge_sub", size=11, label="total_charge_sub")
	public int getTotalChargeSub(){
		return this.totalChargeSub;
	}
	
	@AntColumn(name="total_fee", size=11, label="total_fee")
	public void setTotalFee(int totalFee){
		this.totalFee = totalFee;
	}
	
	@AntColumn(name="total_fee", size=11, label="total_fee")
	public int getTotalFee(){
		return this.totalFee;
	}
	
	@Override
	public String toString() {
		return "["
			+ "timeReport=" + timeReport
			+ ", registered=" + registered
			+ ", unregistered=" + unregistered
			+ ", topPl1=" + topPl1
			+ ", topPl2=" + topPl2
			+ ", topPl3=" + topPl3
			+ ", topPl4=" + topPl4
			+ ", totalChargeSub=" + totalChargeSub
			+ ", totalFee=" + totalFee
			+ "]";
	}
	
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}